Stamptool: fixed causing cairo error
Fixed causing cairo error which is

Error: invalid value (typically too big) for the size of the input
(surface, pattern, etc.)

This came from stamp.get_bbox() returned wrong bbox,
it was actually, area(sx, sy, ex, ey). not rect(x,y,w,h).

Using 'area' should be obsolute...